# Example ESPHome configuration for Catnip I2C Soil Moisture Sensor
# This sensor is based on the Chirp/Catnip I2C soil moisture sensor
# https://github.com/Miceuz/i2c-moisture-sensor

esphome:
  name: soil-moisture-sensor
  platform: ESP32  # or ESP8266
  board: esp32dev  # adjust to your board

wifi:
  ssid: "YourSSID"
  password: "YourPassword"

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:

# I2C Bus configuration
i2c:
  sda: GPIO21  # Adjust to your setup
  scl: GPIO22  # Adjust to your setup
  scan: true
  id: bus_a

# External components
external_components:
  - source:
      type: local
      path: components

# Sensor configuration
sensor:
  - platform: catnip_soil_sensor
    id: soil_sensor
    address: 0x20  # Default address, can be changed
    update_interval: 60s
    i2c_id: bus_a  # Reference to the I2C bus defined above

    # Raw capacitance value
    capacitance:
      name: "Soil Capacitance"
      id: capacitance_raw

    # Temperature in Celsius
    temperature:
      name: "Soil Temperature"
      id: soil_temp

    # Light sensor (higher values = darker)
    light:
      name: "Soil Light Level"
      id: light_level
